force-app/main/default/objects/APEX_Customer__c/APEX_Customer__c.object-meta.xml
<CustomObject>
    <description>Information related to customers</description>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APEX_Customer__c/fields/APEX_Customer_Description__c.field-meta.xml
<CustomField>
    <fullName>APEX_Customer_Description__c</fullName>
    <label>Customer Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APEX_Customer__c/fields/APEX_Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>APEX_Customer_Status__c</fullName>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomerController.cls
public class CustomerController {
    public APEX_Customer__c Customer{get; private set;}
    
    public CustomerController()
    {
        Id id = ApexPages.CurrentPage().getParameters().get('id');
        Customer = id==null ? new APEX_Customer__c() : [Select id, Name, APEX_Customer_Status__c, APEX_Customer_Description__c from APEX_Customer__c where id=:id]; 
    }
    
    public PageReference Save()
    {
        try
        {
            Upsert(Customer);
        }
        catch(System.DMLException e)
        {
            ApexPages.addMessages(e);
            return null;
        }
        PageReference pr=new ApexPages.StandardController(Customer).View();
        return pr;
    
    }
}