force-app/main/default/objects/APEX_Customer__c/APEX_Customer__c.object-meta.xml
<CustomObject>
    <description>Information related to customers</description>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APEX_Customer__c/fields/APEX_Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>APEX_Customer_Status__c</fullName>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APEX_Invoice__c/APEX_Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/APEX_Invoice__c/fields/APEX_Customer__c.field-meta.xml
<CustomField>
    <fullName>APEX_Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>APEX_Customer__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CustomerTriggerTestClass.cls
@isTest
private class CustomerTriggerTestClass
{
    static TestMethod void MyUnitTest()
    {
        //Create Object to test
        APEX_Customer__c custObject = new APEX_Customer__c();
        custObject.APEX_Customer_Status__c = 'Inactive';
        custObject.Name = 'Unit Test Customer';
        Insert custObject;
        
        //Start Testing 
        Test.StartTest();
        custObject.APEX_Customer_Status__c = 'Active';
        Update custObject;
        Test.StopTest();
        //Stop testing
        
        //Check the result or Assert
        List<APEX_Invoice__c> invObject = [select id, APEX_Customer__c from APEX_Invoice__c where APEX_Customer__c =:custObject.Id];
        System.AssertEquals(1,invObject.Size());
        
    }
    
    static TestMethod  void MyUnitTest1()
    {
        //Create Object to test
        APEX_Customer__c custObject = new APEX_Customer__c();
        custObject.APEX_Customer_Status__c = 'Inactive';
        custObject.Name = 'Unit Test Customer';
        Insert custObject;
        
        //Start Testing 
        Test.StartTest();
        custObject.APEX_Customer_Status__c = 'Pending';
        Update custObject;
        Test.StopTest();
        //Stop testing
        
        //Check the result or Assert
        List<APEX_Invoice__c> invObject = [select id, APEX_Customer__c from APEX_Invoice__c where APEX_Customer__c =:custObject.Id];
        System.AssertEquals(0,invObject.Size());
        
    }
}