force-app/main/default/objects/Quiz__c/Quiz__c.object-meta.xml
<CustomObject>
    <label>Quiz</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quiz__c/fields/Qusstion__c.field-meta.xml
<CustomField>
    <fullName>Qusstion__c</fullName>
    <label>Qusstion</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuizControlller.cls
public class QuizControlller 
{
    public List<Quiz__c> quizTemp = new List<Quiz__c>();
    public string answer{get;set;}
    public string query{get;set;}
    public string result{get;set;}
    
    public QuizControlller()
    {
    
    }
    
    public List<SelectOption> questionList
    {
        get
        {
            quizTemp = [Select Id, Qusstion__c From Quiz__c];
            
            questionList = new List<SelectOption>();
            
            for(Quiz__c temp : quizTemp)
            {
                questionList.add(new SelectOption(temp.Id,temp.Qusstion__c));
            }
            return questionList;
        }
        set;
    }
    
    public void validate()
    {
        List<Quiz__c> answerData = [Select Answer__c From Quiz__c where id=:query];
        string answerExact;
        for(Quiz__c ans : answerData)
        {
            answerExact = ans.Answer__c;
        }
        
        if(answer.equalsIgnoreCase(answerExact))
        {
            result='Congratulations its correct';
        }
        else
        {
            result='Alas its wrong';
        }
    }
    
    public PageReference validateNext()
    {
        List<Quiz__c> answerData = [Select Answer__c From Quiz__c where id=:query];
        string answerExact;
        for(Quiz__c ans : answerData)
        {
            answerExact = ans.Answer__c;
        }
        
        if(answer.equalsIgnoreCase(answerExact))
        {
            result='Congratulations its correct';
        }
        else
        {
            result='Alas its wrong';
        }
        
        PageReference requestPage = Page.QuizUINext;
		requestPage.setRedirect(false);
		return requestPage;
    }
}