force-app/main/default/objects/EazzyMovieApiKey__c/EazzyMovieApiKey__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>EazzyMovie ApiKey</label>
</CustomObject>

force-app/main/default/objects/MovieFeedback__c/MovieFeedback__c.object-meta.xml
<CustomObject>
    <label>MovieFeedback</label>
    <nameField>
        <displayFormat>MF-{00000}</displayFormat>
        <label>Movie Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>movieFeedbacks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MovieFeedback__c/fields/Movie_Name__c.field-meta.xml
<CustomField>
    <fullName>Movie_Name__c</fullName>
    <label>Movie Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MovieFeedback__c/fields/Movie_Overall_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Movie_Overall_Feedback__c</fullName>
    <label>Movie Overall Feedback</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MovieFeedback__c/fields/Movie_Part_You_Liked__c.field-meta.xml
<CustomField>
    <fullName>Movie_Part_You_Liked__c</fullName>
    <label>Movie Part You Liked</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MovieFeedback__c/fields/Movie_Rating__c.field-meta.xml
<CustomField>
    <fullName>Movie_Rating__c</fullName>
    <label>Movie Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MovieFeedback__c/fields/Movie_Watch_Date__c.field-meta.xml
<CustomField>
    <fullName>Movie_Watch_Date__c</fullName>
    <label>Movie Watch Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MovieFeedback__c/fields/Movie_Would_You_Recommend__c.field-meta.xml
<CustomField>
    <fullName>Movie_Would_You_Recommend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Movie Would You Recommend?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MovieFeedback__c/fields/User_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>User_Mobile_Number__c</fullName>
    <label>User Mobile Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/EazzyMovieClass.cls
public with sharing class EazzyMovieClass {
    
    @AuraEnabled(cacheable=true)
    public static EazzyMovieResponse getMovieList(String title)
    {
        EazzyMovieResponse responseData = new EazzyMovieResponse();
        try
        {
            EazzyMovieApiKey__c eazzyApi = EazzyMovieApiKey__c.getValues('EazzyMovie');
            String apiKey = eazzyApi.API_Key__c;
            title = EncodingUtil.urlEncode(title,'UTF-8');
            String endpoint = 'callout:EazzyMovie/?apikey='+apiKey+'&s='+title;
            //String endpoint = 'callout:EazzyMovie/?s='+title;
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint(endpoint);
            //request.setHeader('APIKEY', '{!$Credential.Password}');
            //request.setHeader('Authorization', 'apikey={!$Credential.Password}');
            request.setMethod('GET');
            HttpResponse response = http.send(request);
            responseData = EazzyMovieResponse.parse(response.getBody());
            if(responseData.Search!=null)
                for(EazzyMovieResponse.Search sc :responseData.Search)
                	sc.radio=false;
            return responseData;
        }
        catch(Exception ex)
        {
            System.debug(ex.getLineNumber()+ex.getStackTraceString()+ex.getMessage());
            return null;
        }
    }
    
    @AuraEnabled
    public static Boolean SubmitFeedback(String feedData)
    {
        try
        {
            Map<String, Object> requestData = (Map<String, Object>) JSON.deserializeUntyped(feedData);
            MovieFeedback__c movieFeedback = new MovieFeedback__c();
            movieFeedback.Movie_Overall_Feedback__c=(String)requestData.get('Feedback');
            movieFeedback.Movie_Would_You_Recommend__c=Boolean.valueOf(requestData.get('Recommend'));
            movieFeedback.Movie_Part_You_Liked__c=(String)requestData.get('PartYouLiked');
            movieFeedback.Movie_Rating__c=Integer.valueOf(requestData.get('Rating'));
            String movieDate = String.valueOf(requestData.get('Date'));
            movieFeedback.Movie_Watch_Date__c=Date.valueOf(movieDate);
            movieFeedback.User_Mobile_Number__c=(String)requestData.get('Mobile');
            movieFeedback.User_Email__c=(String)requestData.get('Email');
            movieFeedback.User_Name__c=(String)requestData.get('Name');
            movieFeedback.Movie_Name__c=(String)requestData.get('MovieName');
            Database.SaveResult saveResult=Database.insert(movieFeedback);
            return saveResult.isSuccess();
        }
        catch(Exception ex)
        {
            return false;
        }
        
    }
    
    
}