force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/isMovieFinished__c.field-meta.xml
<CustomField>
    <fullName>isMovieFinished__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isMovieFinished</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Movie_Description__c.field-meta.xml
<CustomField>
    <fullName>Movie_Description__c</fullName>
    <label>Movie Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Movie_Image__c.field-meta.xml
<CustomField>
    <fullName>Movie_Image__c</fullName>
    <label>Movie Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/Movie_Theater__c.object-meta.xml
<CustomObject>
    <label>Movie Theater</label>
    <nameField>
        <label>Movie Theater Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movie Theaters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie_Theater__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Movie Theaters</relationshipLabel>
    <relationshipName>Movie_Theaters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Movie_Timings__c.field-meta.xml
<CustomField>
    <fullName>Movie_Timings__c</fullName>
    <label>Movie Timings</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <label>Screen</label>
    <referenceTo>Screen__c</referenceTo>
    <relationshipLabel>Movie Theaters</relationshipLabel>
    <relationshipName>Movie_Theaters</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_A_1__c.field-meta.xml
<CustomField>
    <fullName>Seat_A_1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat A 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_A_2__c.field-meta.xml
<CustomField>
    <fullName>Seat_A_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat A 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_A_3__c.field-meta.xml
<CustomField>
    <fullName>Seat_A_3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat A 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_A_4__c.field-meta.xml
<CustomField>
    <fullName>Seat_A_4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat A 4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_A_5__c.field-meta.xml
<CustomField>
    <fullName>Seat_A_5__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat A 5</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_B_1__c.field-meta.xml
<CustomField>
    <fullName>Seat_B_1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat B 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_B_2__c.field-meta.xml
<CustomField>
    <fullName>Seat_B_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat B 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_B_3__c.field-meta.xml
<CustomField>
    <fullName>Seat_B_3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat B 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_B_4__c.field-meta.xml
<CustomField>
    <fullName>Seat_B_4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat B 4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_B_5__c.field-meta.xml
<CustomField>
    <fullName>Seat_B_5__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat B 5</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_C_1__c.field-meta.xml
<CustomField>
    <fullName>Seat_C_1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat C 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_C_2__c.field-meta.xml
<CustomField>
    <fullName>Seat_C_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat C 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_C_3__c.field-meta.xml
<CustomField>
    <fullName>Seat_C_3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat C 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_C_4__c.field-meta.xml
<CustomField>
    <fullName>Seat_C_4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat C 4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_C_5__c.field-meta.xml
<CustomField>
    <fullName>Seat_C_5__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat C 5</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_D_1__c.field-meta.xml
<CustomField>
    <fullName>Seat_D_1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat D 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_D_2__c.field-meta.xml
<CustomField>
    <fullName>Seat_D_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat D 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_D_3__c.field-meta.xml
<CustomField>
    <fullName>Seat_D_3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat D 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_D_4__c.field-meta.xml
<CustomField>
    <fullName>Seat_D_4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat D 4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie_Theater__c/fields/Seat_D_5__c.field-meta.xml
<CustomField>
    <fullName>Seat_D_5__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seat D 5</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Screen__c/Screen__c.object-meta.xml
<CustomObject>
    <label>Screen</label>
    <nameField>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Screen__c/fields/Theater__c.field-meta.xml
<CustomField>
    <fullName>Theater__c</fullName>
    <label>Theater</label>
    <referenceTo>Theater__c</referenceTo>
    <relationshipLabel>Screens</relationshipLabel>
    <relationshipName>Screens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Theater__c/Theater__c.object-meta.xml
<CustomObject>
    <label>Theater</label>
    <nameField>
        <label>Theater Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Theaters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Theater__c/fields/No_of_Seats__c.field-meta.xml
<CustomField>
    <fullName>No_of_Seats__c</fullName>
    <label>No of Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Theater__c/fields/Theater_Address__c.field-meta.xml
<CustomField>
    <fullName>Theater_Address__c</fullName>
    <label>Theater Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MovieTheatreClass.cls
public class MovieTheatreClass {
    
    @AuraEnabled(cacheable=true)
    public static List<Movie__c> getMovies()
    {
        List<Movie__c> lstMovies = [SELECT Id, Movie_Image__c, Movie_Description__c, isMovieFinished__c, 
                                    Name FROM Movie__c WHERE isMovieFinished__c=false];
        if(!lstMovies.isEmpty())
            return lstMovies;
        else
            return null;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<MovieTheatreClass.MovieTheatreWrapper> getTheatres(Id movieId)
    {
        List<Movie_Theater__c> lstMovieTheatres = [SELECT Id, Name, Movie_Timings__c, Movie__c, Screen__c, Screen__r.Theater__c,
                                                   Screen__r.Name, Seat_A_1__c, Seat_A_2__c, Seat_A_3__c, Seat_A_4__c, 
                                                   Seat_A_5__c, Seat_B_1__c, Seat_B_2__c, Seat_B_3__c, Seat_B_4__c, 
                                                   Seat_B_5__c, Seat_C_1__c, Seat_C_2__c, Seat_C_3__c, Seat_C_4__c, 
                                                   Seat_C_5__c, Seat_D_1__c, Seat_D_2__c, Seat_D_3__c, Seat_D_4__c, 
                                                   Seat_D_5__c, Screen__r.Theater__r.Name,
                                                   Screen__r.Theater__r.Theater_Address__c, 
                                                   Screen__r.Theater__r.No_of_Seats__c FROM 
                                                   Movie_Theater__c  WHERE Movie__c =:movieId AND 
                                                   Movie__r.isMovieFinished__c = false];
        if(!lstMovieTheatres.isEmpty())
        {
            List<MovieTheatreClass.MovieTheatreWrapper> lstMovieTheatreWrap = new List<MovieTheatreClass.MovieTheatreWrapper>();
            for(Movie_Theater__c mt : lstMovieTheatres)
                lstMovieTheatreWrap.add(new MovieTheatreClass.MovieTheatreWrapper(mt));
            return lstMovieTheatreWrap;
            
        }
        else
            return null;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<MovieTheatreClass.MovieTheatreWrapper> getTheatresScreensandTimings(Id movieId, Id theatreId)
    {
        List<Movie_Theater__c> lstMovieTheatres = [SELECT Id, Name, Movie_Timings__c, Movie__c, Screen__c, Screen__r.Theater__c,
                                                   Screen__r.Name, Seat_A_1__c, Seat_A_2__c, Seat_A_3__c, Seat_A_4__c, 
                                                   Seat_A_5__c, Seat_B_1__c, Seat_B_2__c, Seat_B_3__c, Seat_B_4__c, 
                                                   Seat_B_5__c, Seat_C_1__c, Seat_C_2__c, Seat_C_3__c, Seat_C_4__c, 
                                                   Seat_C_5__c, Seat_D_1__c, Seat_D_2__c, Seat_D_3__c, Seat_D_4__c, 
                                                   Seat_D_5__c, Screen__r.Theater__r.Name,
                                                   Screen__r.Theater__r.Theater_Address__c, 
                                                   Screen__r.Theater__r.No_of_Seats__c FROM 
                                                   Movie_Theater__c WHERE Movie__c =:movieId AND 
                                                   Movie__r.isMovieFinished__c = false AND
                                                   Screen__r.Theater__c=:theatreId];
        if(!lstMovieTheatres.isEmpty())
        {
            List<MovieTheatreClass.MovieTheatreWrapper> lstMovieTheatreWrap = new List<MovieTheatreClass.MovieTheatreWrapper>();
            for(Movie_Theater__c mt : lstMovieTheatres)
                lstMovieTheatreWrap.add(new MovieTheatreClass.MovieTheatreWrapper(mt));
            return lstMovieTheatreWrap;
            
        }
        else
            return null;
    }
    
    
    @AuraEnabled(cacheable=true)
    public static MovieTheatreClass.MovieTheatreWrapper getAvailableSeats(Id movieTheatreId)
    {
        List<Movie_Theater__c> lstMovieTheatres = [SELECT Id, Name, Movie_Timings__c, Movie__c, Screen__c, Screen__r.Theater__c,
                                                   Screen__r.Name, Seat_A_1__c, Seat_A_2__c, Seat_A_3__c, Seat_A_4__c, 
                                                   Seat_A_5__c, Seat_B_1__c, Seat_B_2__c, Seat_B_3__c, Seat_B_4__c, 
                                                   Seat_B_5__c, Seat_C_1__c, Seat_C_2__c, Seat_C_3__c, Seat_C_4__c, 
                                                   Seat_C_5__c, Seat_D_1__c, Seat_D_2__c, Seat_D_3__c, Seat_D_4__c, 
                                                   Seat_D_5__c, Screen__r.Theater__r.Name,
                                                   Screen__r.Theater__r.Theater_Address__c, 
                                                   Screen__r.Theater__r.No_of_Seats__c FROM 
                                                   Movie_Theater__c WHERE Id =:movieTheatreId];
        if(!lstMovieTheatres.isEmpty())
        	return new MovieTheatreClass.MovieTheatreWrapper(lstMovieTheatres[0]);
        else
            return null;
    }
    
    public class MovieTheatreWrapper {
        @AuraEnabled public Object Name;
        @AuraEnabled public Object MovieTheatreId;
        @AuraEnabled public Object Movie_Timings;
        @AuraEnabled public Object Movie;
        @AuraEnabled public Object Theater;
        @AuraEnabled public Object Screen;
        @AuraEnabled public Object Screen_Name;
        @AuraEnabled public Object Theater_Name;
        @AuraEnabled public Object Theater_Address;
        @AuraEnabled public Object Theater_No_of_Seats;
        @AuraEnabled public Object Seat_A_1;
        @AuraEnabled public Object Seat_A_2;
        @AuraEnabled public Object Seat_A_3;
        @AuraEnabled public Object Seat_A_4;
        @AuraEnabled public Object Seat_A_5;
        @AuraEnabled public Object Seat_B_1;
        @AuraEnabled public Object Seat_B_2;
        @AuraEnabled public Object Seat_B_3;
        @AuraEnabled public Object Seat_B_4;
        @AuraEnabled public Object Seat_B_5;
        @AuraEnabled public Object Seat_C_1;
        @AuraEnabled public Object Seat_C_2;
        @AuraEnabled public Object Seat_C_3;
        @AuraEnabled public Object Seat_C_4;
        @AuraEnabled public Object Seat_C_5;
        @AuraEnabled public Object Seat_D_1;
        @AuraEnabled public Object Seat_D_2;
        @AuraEnabled public Object Seat_D_3;
        @AuraEnabled public Object Seat_D_4;
        @AuraEnabled public Object Seat_D_5;
        
        public MovieTheatreWrapper(Movie_Theater__c movieTheatre)
        {
            this.Name = movieTheatre.Name;
            this.MovieTheatreId = movieTheatre.Id;
            this.Movie_Timings = movieTheatre.Movie_Timings__c;
            this.Movie = movieTheatre.Movie__c;
            this.Screen = movieTheatre.Screen__c;
            this.Screen_Name = movieTheatre.Screen__r.Name;
            this.Theater = movieTheatre.Screen__r.Theater__c;
            this.Theater_Name = movieTheatre.Screen__r.Theater__r.Name;
            this.Theater_Address = movieTheatre.Screen__r.Theater__r.Theater_Address__c;
            this.Theater_No_of_Seats = movieTheatre.Screen__r.Theater__r.No_of_Seats__c;
            this.Seat_A_1 = movieTheatre.Seat_A_1__c;
            this.Seat_A_2 = movieTheatre.Seat_A_2__c;
            this.Seat_A_3 = movieTheatre.Seat_A_3__c;
            this.Seat_A_4 = movieTheatre.Seat_A_4__c;
            this.Seat_A_5 = movieTheatre.Seat_A_5__c;
            this.Seat_B_1 = movieTheatre.Seat_B_1__c;
            this.Seat_B_2 = movieTheatre.Seat_B_2__c;
            this.Seat_B_3 = movieTheatre.Seat_B_3__c;
            this.Seat_B_4 = movieTheatre.Seat_B_4__c;
            this.Seat_B_5 = movieTheatre.Seat_B_5__c;
            this.Seat_C_1 = movieTheatre.Seat_C_1__c;
            this.Seat_C_2 = movieTheatre.Seat_C_2__c;
            this.Seat_C_3 = movieTheatre.Seat_C_3__c;
            this.Seat_C_4 = movieTheatre.Seat_C_4__c;
            this.Seat_C_5 = movieTheatre.Seat_C_5__c;
            this.Seat_D_1 = movieTheatre.Seat_D_1__c;
            this.Seat_D_2 = movieTheatre.Seat_D_2__c;
            this.Seat_D_3 = movieTheatre.Seat_D_3__c;
            this.Seat_D_4 = movieTheatre.Seat_D_4__c;
            this.Seat_D_5 = movieTheatre.Seat_D_5__c;
        }
    }
    
    
    
}